arch: fix archinfo and misc for ARM
devitocodes/devito pull request #1510
Opened 2020-11-17 23:53 UTC by jaimesouza

This PR fixes some issues in archinfo.py and misc.py that generated errors when running on ARM (Isambard).

2020-11-18 11:31 UTC, FabioLuporini requested changes
@rhodrin maybe time to add an ARM action to our CI workflows?

2020-11-18 11:31 UTC, FabioLuporini commented on devito/passes/iet/misc.py
> +    if iet.is_ElementalFunction or isinstance(archinfo.get_platform(), archinfo.Arm):
The compilation passes (`iet_pass`) are independent of the underlying architecture.

If you don't want `avoid_denormals` on Arm (even though this appears to be a mere work around) the way to go is to create a suitable compilation pipeline for Arm, which is identical to Intel except for the lack of `avoid_denormals`.

There already exists one such Arm compilation pipeline: https://github.com/devitocodes/devito/blob/master/devito/core/__init__.py#L31 -- as you can see, named `ArmOperator`.

You should go to ArmOperator, intercept (override) `_specialize_iet` so as to drop `avoid_denormals`

2020-11-19 08:17 UTC, FabioLuporini approved these changes
LGTM. 

@georgebisbas can you try this patch?

@rhodrin can we add a free GH Actions runner?

2020-11-19 08:39 UTC, georgebisbas commented
> @georgebisbas can you try this patch?

Yes

2020-11-19 09:57 UTC, georgebisbas commented
I can confirm that the patch works and I could execute
acoustic and elastic operator.

2020-11-19 11:48 UTC, mloubout commented
>can we add a free GH Actions runner?

You mean you want a `CI-arm`? That easily doable or can be added to `CI-cpu` but there is no ARM chips on GH actions.

2020-11-19 17:14 UTC, georgebisbas commented
> > can we add a free GH Actions runner?
> 
> You mean you want a `CI-arm`? That easily doable or can be added to `CI-cpu` but there is no ARM chips on GH actions.

@mloubout : https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/
is that of use?

2020-11-22 21:46 UTC, georgebisbas commented
Closed as superseded by #1515

2020-11-22 21:46 UTC, closed without merging