Loop tiling for GPU
devitocodes/devito pull request #1801
Opened 2021-11-23 17:57 UTC by italoaug

Enable code generation of loop tiling for GPU

2021-11-26 16:33 UTC, georgebisbas reviewed
This PR adds blocking code generation as a secondary option. i.e. not in the advanced pipeline but as a custom pass. I checked myself and seems to be doing what we want. Performance-wise there is no reason to be added in the advanced pipeline as it does not deliver performance. This is expected since nested parallelism pragmas need to be added. This can happen at later PR.

2021-12-01 08:46 UTC, FabioLuporini commented on tests/test_gpu_openacc.py
> +        ('advanced', {'linearize': True}),
this one is probably overkill (never forget that running tests has a cost) provided that we keep the last one, ie `(blocking, {linearize=true})`

2021-12-01 08:46 UTC, FabioLuporini commented on tests/test_gpu_openmp.py
> +        ('advanced', {'linearize': True}),
this one is probably overkill (never forget that running tests has a cost) provided that we keep the last one, ie (blocking, {linearize=true})

2021-12-01 08:46 UTC, FabioLuporini commented on tests/test_gpu_openacc.py
> +        ('blocking', ),
this one is probably overkill since blocking is already tested below in tandem with linearize

2021-12-01 08:46 UTC, FabioLuporini commented on tests/test_gpu_openmp.py
> +        ('blocking', ),
this one is probably overkill since blocking is already tested below in tandem with linearize

2021-12-01 08:46 UTC, FabioLuporini commented on tests/test_gpu_openmp.py
> +        TestOperator().iso_acoustic(opt=('advanced', {}))
opt='advanced'

2021-12-01 08:46 UTC, FabioLuporini commented on tests/test_gpu_openmp.py
> +        ('advanced', {}),
'advanced' should suffice

2021-12-02 08:36 UTC, FabioLuporini approved these changes

2021-12-02 08:38 UTC, FabioLuporini requested changes
The code is OK, but the commit history is not. There are two main issues:

* Far too many commits for just a few line edits. You'll need to squash away some of them
* The commit messages do not honor the format. See [here](https://github.com/devitocodes/devito/wiki/Tags-for-commit-messages-and-PR-titles)

2021-12-03 07:43 UTC, FabioLuporini approved these changes

2021-12-03 07:43 UTC, FabioLuporini commented
Merging, thanks

2021-12-03 07:43 UTC, merged