tests: Add test and patch for issue 2325
devitocodes/devito pull request #2416
Opened 2024-07-19 13:28 UTC by EdCaunt

Fixes #2325.

2024-07-19 18:10 UTC, mloubout requested changes
I don't really see what's the issue there and why we would need two separate properties. 
If the factor is None it will rebuild with factor=1 that is treated as None so it will rebuild correctly so I don't see where the issue is

2024-07-20 02:08 UTC, mloubout commented
I don't see anything wrong on master

```

In [1]: from devito import *

In [2]: x = Dimension(name='x')
   ...: cd = ConditionalDimension(name='cd', parent=x, condition=Ge(x, 1))

In [3]: cd._rebuild()._factor

In [4]: cd._rebuild().factor
Out[4]: 1

In [5]: cd.factor
Out[5]: 1

In [6]: cd._factor


```

2024-07-22 07:40 UTC, georgebisbas commented on devito/types/dimension.py
> +        return self._factor
Cant this be `return self._factor or 1`
and drop `def factor_default` ?

2024-07-22 08:25 UTC, EdCaunt commented
Looks like this was actually fixed in a separate patch (blame says @mloubout fixed it 5 days ago). Closing.

2024-07-22 08:25 UTC, closed without merging